### ISSUE TITLE
Create test rule for Raccoon unit and tear down

### ISSUE THREAD

**Issue by geoff-powell** [iamjosephmj/Raccoon#15]
Looking at the readme, it might be beneficial to add a junit test rule to setup and teardown Raccoon without adding the extra methods in the test class. It would also allow you to wrap the raccoon test rule around the ActivityTestRule and support launching the activity default.

**Comment by iamjosephmj** [comment]
Great suggestion 👍

**Comment by iamjosephmj** [comment]
@gpowell13  The test rule is now Implemented
https://github.com/iamjosephmj/Raccoon#raccoon-testrule
